replicas: 1
kubernetesVersion: 1.7.5
serviceNetwork: 10.0.0.0/24
podNetwork: 192.168.0.0/16
clusterName: shoot-foo-bar
podAnnotations: {}
podLabels: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  kube-controller-manager: image-repository
horizontalPodAutoscaler:
  downscaleDelay: 15m
  syncPeriod: 30s
  tolerance: 0.1
  upscaleDelay: 1m
  downscaleStabilization: 5m0s
  readinessDelay: 30s
  cpuInitializationPeriod: 5m0s

# serviceAccountAnnotations:
#   a: b

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 512Mi
