apiVersion: druid.gardener.cloud/v1alpha1
kind: Etcd
metadata:
  name: etcd-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
    garden.sapcloud.io/role: controlplane
    role: {{ .Values.role }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  priorityClassName: gardener-shoot-controlplane
{{- if .Values.podAnnotations }}
  annotations:
{{ toYaml .Values.podAnnotations | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      garden.sapcloud.io/role: controlplane
      app: etcd-statefulset
      role: {{ .Values.role }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: etcd-statefulset
    role: {{ .Values.role }}
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-public-networks: allowed
    networking.gardener.cloud/to-private-networks: allowed
  etcd:
{{- if .Values.etcd.resources }}
    resources:
{{ toYaml .Values.etcd.resources | indent 6 }}
{{- end }}
    tls:
      serverTLSSecretRef:
        name: {{ .Values.etcd.tlsServerSecretName }}
        namespace: {{ .Release.Namespace }}
      clientTLSSecretRef:
        name: {{ .Values.etcd.tlsClientSecretName }}
        namespace: {{ .Release.Namespace }}
      tlsCASecretRef:
        name: {{ .Values.etcd.tlsCASecretName }}
        namespace: {{ .Release.Namespace }}
    serverPort: {{ .Values.etcd.serverPort }}
    clientPort: {{ .Values.etcd.clientPort }}
    metrics: {{ .Values.etcd.metrics }}
    defragmentationSchedule: {{ .Values.etcd.defragmentSchedule }}
  backup:
    port: {{ .Values.sidecar.port }}
{{- if .Values.sidecar.resources }}
    resources:
{{ toYaml .Values.sidecar.resources | indent 6 }}
{{- end }}
    quota: {{ .Values.sidecar.quota }}
    garbageCollectionPolicy: {{ .Values.sidecar.garbageCollectionPolicy }}
    garbageCollectionPeriod: {{ .Values.sidecar.garbageCollectionPeriod }}
    maxBackups: {{ .Values.sidecar.maxBackups }}
{{- if .Values.sidecar.backup }}
    store:
      secretRef:
        name: {{ .Values.sidecar.backup.secretRefName }}
      container: {{ .Values.sidecar.backup.container }}
      provider: {{ .Values.sidecar.backup.provider }}
      prefix: {{ .Values.sidecar.backup.prefix }}/etcd-{{ .Values.role }}
    fullSnapshotSchedule: {{ .Values.sidecar.backup.fullSnapshotSchedule }}
    deltaSnapshotPeriod: {{ .Values.sidecar.backup.deltaSnapshotPeriod }}
    deltaSnapshotMemoryLimit: {{ .Values.sidecar.backup.deltaSnapshotMemoryLimit }}
{{- end }}
{{- if .Values.storageClass }}
  storageClass: {{ .Values.storageClass }}
{{- end }}
  storageCapacity: {{ .Values.storageCapacity }}
{{- if eq .Values.role "main" }}
  volumeClaimTemplate: {{ .Values.role }}-etcd
{{- else }}
  volumeClaimTemplate: etcd-{{ .Values.role }}
{{- end }}
