{{ if .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  name: etcd-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: etcd-statefulset
    role: {{ .Values.role }}
spec:
  replicas: 1
{{- if .Values.hvpa.maintenanceWindow }}
  maintenanceTimeWindow:
{{ toYaml .Values.hvpa.maintenanceWindow | indent 4 }}
{{- end }}
  hpa:
    selector:
      matchLabels:
        role: etcd-hpa-{{ .Values.role }}
    deploy: false
    template:
      metadata:
        labels:
          role: etcd-hpa-{{ .Values.role }}
      spec:
        maxReplicas: {{ .Values.replicas }}
        minReplicas: {{ .Values.replicas }}
        metrics:
        - resource:
            name: memory
            targetAverageUtilization: {{ .Values.hvpa.targetAverageUtilizationMemory }}
          type: Resource
        - resource:
            name: cpu
            targetAverageUtilization: {{ .Values.hvpa.targetAverageUtilizationCpu }}
          type: Resource
  vpa:
    selector:
      matchLabels:
        role: etcd-vpa-{{ .Values.role }}
    deploy: true
    scaleUp:
      updatePolicy:
        updateMode: "Initial"
{{- if .Values.hvpa.scaleUpStabilization }}
{{ toYaml .Values.hvpa.scaleUpStabilization | indent 6 }}
{{- end }}
    scaleDown:
      updatePolicy:
        updateMode: "MaintenanceWindow"
{{- if .Values.hvpa.scaleDownStabilization }}
{{ toYaml .Values.hvpa.scaleDownStabilization | indent 6 }}
{{- end }}
{{- if .Values.hvpa.limitsRequestsGapScaleParams }}
    limitsRequestsGapScaleParams:
{{ toYaml .Values.hvpa.limitsRequestsGapScaleParams | indent 6 }}
{{- end }}
    template:
      metadata:
        labels:
          role: etcd-vpa-{{ .Values.role }}
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: etcd
              maxAllowed:
                memory: {{ .Values.hvpa.maxAllowed.memory }}
                cpu:  "{{ .Values.hvpa.maxAllowed.cpu }}"
              minAllowed:
                memory: {{ .Values.hvpa.minAllowed.memory }}
                cpu: "{{ .Values.hvpa.minAllowed.cpu }}"
            - containerName: backup-restore
              mode: "Off"
  weightBasedScalingIntervals:
    - vpaWeight: 100
      startReplicaCount: {{ .Values.replicas }}
      lastReplicaCount: {{ .Values.replicas }}
  targetRef:
    apiVersion:  {{ include "statefulsetversion" . }}
    kind: StatefulSet
    name: etcd-{{ .Values.role }}
{{ end }}
{{ end }}
