apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
{{- end }}
