replicas: 1
role: for-test
labels: {}
annotations: {}
podAnnotations: {}

etcd:
  resources:
    requests:
      cpu: 300m
      memory: 1G
    limits:
      cpu: 900m
      memory: 3G
  tlsCASecretName: ca-etcd
  tlsServerSecretName: etcd-server-cert
  tlsClientSecretName: etcd-client-tls
  serverPort: 2380
  clientPort: 2379
  defragmentSchedule: "0 */24 * * *"
  metrics: basic

sidecar:
  resources:
    limits:
      cpu: "1"
      memory: 10G
    requests:
      cpu: 23m
      memory: 128Mi
  port: 8080
  quota: 8Gi
  garbageCollectionPeriod: 12h
  garbageCollectionPolicy: LimitBased
  maxBackups: 3
# backup:
#   provider: aws
#   container: temp
#   secretRefName: etcd-backup
#   prefix: temp
#   fullSnapshotSchedule: "0 */24 * * *"
#   deltaSnapshotMemoryLimit: 100Mi
#   deltaSnapshotPeriod: 5m

#storageClass: gardener.cloud-fast
storageCapacity: 16Gi

hvpa:
  enabled: false
  maxAllowed:
    cpu: "4"
    memory: 30G
  minAllowed:
    cpu: 200m
    memory: 700M
  targetAverageUtilizationCpu: 80
  targetAverageUtilizationMemory: 80
# maintenanceWindow: <time-window>
  scaleUpStabilization:
    stabilizationDuration: "5m"
    minChange:
      cpu:
        value: "1"
        percentage: 80
      memory:
        value: 2G
        percentage: 80
  scaleDownStabilization:
    stabilizationDuration: "15m"
    minChange:
      cpu:
        value: "1"
        percentage: 80
      memory:
        value: 2G
        percentage: 80
  limitsRequestsGapScaleParams:
    cpu:
      value: "3"
      percentage: 80
    memory:
      value: "5G"
      percentage: 80
