{{- if .Values.global.gardenlet.vpa }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: gardenlet-vpa
  namespace: garden
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: gardenlet
  updatePolicy:
    updateMode: Initial
{{- end }}
