{{ if not .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
apiVersion: {{ include "hpaversion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  scaleTargetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: kube-apiserver
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationCpu }}
{{/* Disable memory calculation which is meaningless */}}
{{/*  - type: Resource*/}}
{{/*    resource:*/}}
{{/*      name: memory*/}}
{{/*      targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationMemory }}*/}}
{{- end }}
{{ end }}
