{{ if .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
{{- if .Values.maintenanceWindow }}
  maintenanceTimeWindow:
{{ toYaml .Values.maintenanceWindow | indent 4 }}
{{- end }}
  hpa:
    selector:
      matchLabels:
        role: apiserver-hpa
    deploy: true
    scaleUp:
      updatePolicy:
        updateMode: "Initial"
    scaleDown:
      updatePolicy:
        updateMode: "Initial"
    template:
      metadata:
        labels:
          role: apiserver-hpa
      spec:
        maxReplicas: {{ .Values.maxReplicas }}
        minReplicas: {{ .Values.minReplicas }}
        metrics:
{{- if .Values.hpa.memoryMetricForHpaEnabled }}
        - resource:
            name: memory
            targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationMemory }}
          type: Resource
{{- end }}
        - resource:
            name: cpu
            targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationCpu }}
          type: Resource
  vpa:
    selector:
      matchLabels:
        role: apiserver-vpa
    deploy: true
    scaleUp:
      updatePolicy:
        updateMode: "Initial"
{{- if .Values.scaleUpStabilization }}
{{ toYaml .Values.scaleUpStabilization | indent 6 }}
{{- end }}
    scaleDown:
      updatePolicy:
        updateMode: "Initial"
{{- if .Values.scaleDownStabilization }}
{{ toYaml .Values.scaleDownStabilization | indent 6 }}
{{- end }}
{{- if .Values.limitsRequestsGapScaleParams }}
    limitsRequestsGapScaleParams:
{{ toYaml .Values.limitsRequestsGapScaleParams | indent 6 }}
{{- end }}
    template:
      metadata:
        labels:
          role: apiserver-vpa
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: kube-apiserver
              maxAllowed:
                memory: 25G
                cpu: "8"
              minAllowed:
                memory: 400M
                cpu: 300m
            - containerName: vpn-seed
              mode: "Off"
  weightBasedScalingIntervals:
{{- if gt (int .Values.maxReplicas) (int .Values.minReplicas) }}
    - vpaWeight: 0
      startReplicaCount: {{ .Values.minReplicas }}
      lastReplicaCount: {{ sub (int .Values.maxReplicas) 1 }}
{{- end }}
    - vpaWeight: 100
      startReplicaCount: {{ .Values.maxReplicas }}
      lastReplicaCount: {{ .Values.maxReplicas }}
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: kube-apiserver
{{ end }}
{{ end }}
